INHERIT: '../base.yml'

docs_dir: '../../src/zh-Hans'
site_dir: '../../build/zh-Hans'

theme:
  name: material
  language: zh

plugins:
  - search
  - tags:
      tags_file: tags.md
  - social:
      cards_layout_options:
        background_color: "#14151A"
        font_family: Noto Sans SC

site_description: '一些世界各地的摇摆舞活动相关信息收录。'
nav:
  - 首页:
    - 时间线: index.md
    - 标签: tags.md
    #- 存档:

  - 地区:
    - 所有: regions.md
    - 美洲:
      - 加拿大:
        - 时间线: ca/index.md
        - 按城市划分: ca/by_city.md
        - 主办城市: ca/host_cities.md
        - 已收录活动:
          - ca/victoria-lindy-exchange.md
          - ca/stardust-festival.md
          - ca/rhythm-city-mess-around.md
          - ca/lindy-harvest.md
          - ca/cats-corner-exchange.md
          - ca/vancouver-balboa-mini-fest.md
          - ca/capital-city-stomp.md
      - 智利:
        - 时间线: cl/index.md
        - 按城市划分: cl/by_city.md
        - 主办城市: cl/host_cities.md
        - 已收录活动:
          - cl/lindy-poh.md
      - 墨西哥:
        - 时间线: mx/index.md
        - 按城市划分: mx/by_city.md
        - 主办城市: mx/host_cities.md
        - 已收录活动:
          - mx/mexico-lindy-querido.md
          - mx/guadalajara-lindy-exchange.md
          - mx/lindy-n-balboa-maya-fest.md
      - 美国:
        - 时间线: us/index.md
        - 按城市划分: us/by_city.md
        - 主办城市: us/host_cities.md
        - 已收录活动:
          - us/california-balboa-classic.md
          - us/hot-rhythm-holiday.md
          - us/lindyfest.md
          - us/bal-week.md
          - us/back-home-again.md
          - us/san-diego-balboa-and-lindy-exchange.md
          - us/flying-home.md
          - us/camp-hollywood.md
          - us/cincy-hop.md
          - us/rittenhopalooza.md
          - us/summer-swing-fest.md
          - us/swing-out-new-hampshire.md
          - us/the-uptown-swingout.md
          - us/blues-fusion-dfw.md
          - us/cowtown-jamborama.md
          - us/express-track-blues.md
          - us/great-lakes-balboa-escape.md
          - us/hot-night-fusion-weekend.md
          - us/lindy-on-the-rocks.md
          - us/new-york-lindy-exchange.md
          - us/rhythm-shuffle.md
          - us/blues-muse.md
          - us/bubble-city-bash.md
          - us/emerald-city-blues-festival.md
          - us/stl-getdown.md
          - us/the-american-lindy-hop-championships.md
          - us/whistle-stop.md
          - us/austin-lindy-exchange.md
          - us/breaking-bal-swing-n-blues-weekend.md
          - us/hot-jazz-jamboree.md
          - us/stardust-slow-balboa-weekend.md
          - us/stompology.md
          - us/stormy-weather-jazz-festival.md
    - 亚洲:
      - 亚美尼亚:
        - 时间线: am/index.md
        - 按城市划分: am/by_city.md
        - 主办城市: am/host_cities.md
        - 已收录活动:
          - am/swing-road-armenia.md
      - 中国:
        - 时间线: cn/index.md
        - 按城市划分: cn/by_city.md
        - 主办城市: cn/host_cities.md
        - 已收录活动:
          - cn/beijing-balboa-travel.md
          - cn/down-south-camp-meeting.md
          - cn/its-solo-king.md
          - cn/all-balboa-exchange.md
          - cn/canton-swing-festival.md
          - cn/groove-the-bluesy-bay.md
          - cn/lindy-hotpot.md
          - cn/balboa-spring-camp.md
          - cn/shanghai-blues-camp.md
          - cn/bouncy-chengdu.md
          - cn/suzhou-lindy-festival.md
          - cn/jumpin-swing.md
          - cn/baliday.md
          - cn/nanjing-lindy-festival.md
          - cn/beijing-balboa-fever.md
          - cn/dragon-boat-swing-camp.md
          - cn/jump-for-joy.md
          - cn/swing-in-dalifornia.md
          - cn/urumqi-swing-exchange.md
          - cn/balboa-festival.md
          - cn/bal-in-beijing.md
          - cn/balboa-festival-shanghai.md
          - cn/funs-swing-exchange.md
          - cn/blues-heat.md
          - cn/blues-in-green.md
          - cn/swing-feast.md
          - cn/westlake-swing-carnival.md
          - cn/jazz-do-it.md
          - cn/beijing-blues-bush.md
          - cn/golden-bal-week.md
          - cn/island-swing.md
          - cn/swing-paramount.md
          - cn/womens-jazzination.md
          - cn/camp-california-weekend.md
          - cn/hop-the-bay.md
          - cn/swing-to-the-stars.md
          - cn/shanghai-balboa-weekend.md
          - cn/swingtime-ball.md
          - cn/foshan-x-korea-exchange.md
          - cn/shanghai-lindy-festival.md
      - 香港:
        - 时间线: hk/index.md
        - 按城市划分: hk/by_city.md
        - 主办城市: hk/host_cities.md
        - 已收录活动:
          - hk/harbourside-swing-fest.md
      - 印尼:
        - 时间线: id/index.md
        - 按城市划分: id/by_city.md
        - 主办城市: id/host_cities.md
        - 已收录活动:
          - id/bali-lindy-exchange.md
      - 日本:
        - 时间线: jp/index.md
        - 按城市划分: jp/by_city.md
        - 主办城市: jp/host_cities.md
        - 已收录活动:
          - jp/balboa-lab-tea-party.md
          - jp/chill-balboa-social.md
          - jp/swingin-n-hoppin-sapporp.md
          - jp/tomodachi-swing.md
          - jp/bal-in-tokyo.md
          - jp/swing-jack.md
          - jp/osaka-lindy-exchange.md
          - jp/tokyo-balboa-weekend.md
      - 韩国:
        - 时间线: kr/index.md
        - 按城市划分: kr/by_city.md
        - 主办城市: kr/host_cities.md
        - 已收录活动:
          - kr/blues-alive.md
          - kr/asia-balboa-exchange.md
          - kr/camp-swing-it.md
          - kr/rhythm-korea.md
          - kr/pulse-in-seoul.md
          - kr/champions-cup-korea.md
          - kr/bal-hop.md
          - kr/jump-to-berlin.md
          - kr/seoul-lindy-fest.md
          - kr/korean-balboa-weekend.md
          - kr/savoy-cup-asia.md
      - 泰国:
        - 时间线: th/index.md
        - 按城市划分: th/by_city.md
        - 主办城市: th/host_cities.md
        - 已收录活动:
          - th/breezy-balboa.md
          - th/swing-era.md
          - th/diga-diga-doo.md
      - 土耳其:
        - 时间线: tr/index.md
        - 按城市划分: tr/by_city.md
        - 主办城市: tr/host_cities.md
        - 已收录活动:
          - tr/jumpin-at-istanbul.md
      - 台湾:
        - 时间线: tw/index.md
        - 按城市划分: tw/by_city.md
        - 主办城市: tw/host_cities.md
        - 已收录活动:
          - tw/cheek-to-cheek-swing-festival.md
          - tw/what-the-pa.md
    - 欧洲:
      - 比利时:
        - 时间线: be/index.md
        - 按城市划分: be/by_city.md
        - 主办城市: be/host_cities.md
        - 已收录活动:
          - be/boulevard-blues.md
      - 瑞士:
        - 时间线: ch/index.md
        - 按城市划分: ch/by_city.md
        - 主办城市: ch/host_cities.md
        - 已收录活动:
          - ch/bal-inspiration.md
          - ch/shag-delight.md
          - ch/shake-that-lake.md
          - ch/rocky-balberna.md
          - ch/stir-it.md
      - 捷克:
        - 时间线: cz/index.md
        - 按城市划分: cz/by_city.md
        - 主办城市: cz/host_cities.md
        - 已收录活动:
          - cz/bal-love.md
          - cz/slow-bal-love.md
      - 德国:
        - 时间线: de/index.md
        - 按城市划分: de/by_city.md
        - 主办城市: de/host_cities.md
        - 已收录活动:
          - de/slow-balboa-weekend-munich.md
          - de/swing-it-berlin.md
          - de/berlin-balboa-weekend.md
          - de/rock-that-swing-festival.md
          - de/b-t-switch.md
          - de/swingcake-tubingen.md
          - de/harvest-moon-swing-dance-camp.md
          - de/lindy-hop-trainingslager.md
          - de/shag-ahoi.md
          - de/velo-swing-festival.md
          - de/augsburg-balboa-festival.md
          - de/flying-feet-stuttgart.md
          - de/hannover-swing-exchange.md
          - de/hully-blues.md
          - de/swing-it-konstanz.md
          - de/are-you-syncopated.md
          - de/blues-dance-retreat.md
          - de/da-solo-jazz-festival.md
          - de/lindy-cake.md
          - de/mainhatten-shuffle.md
          - de/munich-balboa-n-shag-weekend.md
          - de/swing-man-tau.md
          - de/swingomania.md
          - de/augsburg-boogie-festival.md
          - de/balboa-date-stuttgart.md
          - de/broadway-swing.md
          - de/hully-hop-swing-farm.md
          - de/swingin-charlie.md
          - de/swinging-marzipan-lubeck.md
          - de/autumn-leaves-the-pott.md
          - de/xma-swing.md
      - 丹麦:
        - 时间线: dk/index.md
        - 按城市划分: dk/by_city.md
        - 主办城市: dk/host_cities.md
        - 已收录活动:
          - dk/why-not-aarhus-lindy-exchange.md
          - dk/copenhagen-balboa-weekend.md
          - dk/falling-for-swing.md
      - 西班牙:
        - 时间线: es/index.md
        - 按城市划分: es/by_city.md
        - 主办城市: es/host_cities.md
        - 已收录活动:
          - es/move-your-bottom.md
          - es/sevilla-swing-festival.md
          - es/festival-swing-monachil.md
          - es/jazz-n-swing-gasteiz-festival.md
          - es/metropoli-fest.md
          - es/morella-swing-weekend.md
          - es/barcelona-lindy-exchange.md
          - es/barcelona-shag-festival.md
          - es/calpe-swing-fiesta.md
          - es/swim-out-costa-brava.md
          - es/swing-a-esgaya.md
          - es/the-jump.md
          - es/cadiz-swing-festival.md
          - es/donosti-belle-swing-festival.md
          - es/mojo-swing-tropical-fest.md
          - es/smile-trio-weekend.md
          - es/stomp-your-feet.md
          - es/swing-ciudad-real.md
          - es/swing-fest-malaga.md
          - es/barcelona-balboa-festival.md
          - es/espanish-blues-festival.md
      - 法国:
        - 时间线: fr/index.md
        - 按城市划分: fr/by_city.md
        - 主办城市: fr/host_cities.md
        - 已收录活动:
          - fr/the-battle.md
          - fr/tours-n-swing.md
          - fr/swing-art-festival.md
          - fr/anduze-jazz-dance-camp.md
          - fr/summer-camp-balboa-week.md
          - fr/summer-camp-lindy-week.md
          - fr/la-plagne-swing.md
          - fr/summer-camp-blues-week.md
          - fr/savoie-balboa-festival.md
          - fr/tours-n-balboa.md
          - fr/rainy-blues.md
          - fr/toulouse-swing-exchange.md
          - fr/lyon-swing-festival.md
          - fr/swingamann.md
          - fr/european-balboa-festival.md
      - 希腊:
        - 时间线: gr/index.md
        - 按城市划分: gr/by_city.md
        - 主办城市: gr/host_cities.md
        - 已收录活动:
          - gr/crete-on-the-beat.md
          - gr/wild-west-festival.md
      - 意大利:
        - 时间线: it/index.md
        - 按城市划分: it/by_city.md
        - 主办城市: it/host_cities.md
        - 已收录活动:
          - it/crazy-blues.md
          - it/keep-on-swingin.md
          - it/milan-balboa-weekend.md
          - it/tuscany-balboa-weekend.md
          - it/swing-in-roma.md
          - it/roma-balboa-weekend.md
          - it/swing-train-festival.md
          - it/sunny-slide-swing-fest.md
          - it/swing-in-the-amalfi-coast.md
          - it/bal-n-lindy-vintage-festival.md
          - it/balboario.md
          - it/policoro-in-swing.md
          - it/sicily-swing-fest.md
          - it/swingala.md
          - it/swing-n-milan.md
      - 立陶宛:
        - 时间线: lt/index.md
        - 按城市划分: lt/by_city.md
        - 主办城市: lt/host_cities.md
        - 已收录活动:
          - lt/uptown-rhythm.md
          - lt/bluesila.md
          - lt/what-a-jazz-summer-camp.md
          - lt/all-lithuanian-weekend.md
          - lt/vilnius-shag-festival.md
      - 卢森堡:
        - 时间线: lu/index.md
        - 按城市划分: lu/by_city.md
        - 主办城市: lu/host_cities.md
        - 已收录活动:
          - lu/swing-the-abbey.md
      - 荷兰:
        - 时间线: nl/index.md
        - 按城市划分: nl/by_city.md
        - 主办城市: nl/host_cities.md
        - 已收录活动:
          - nl/the-mess-around.md
          - nl/swing-dom.md
          - nl/the-vintage-battle-of-the-bands.md
      - 挪威:
        - 时间线: no/index.md
        - 按城市划分: no/by_city.md
        - 主办城市: no/host_cities.md
        - 已收录活动:
          - no/scandinavian-shuffle.md
          - no/winter-jump.md
          - no/bal-heim.md
          - no/boogie-feets-festival.md
          - no/slow-balboa-boost.md
          - no/o-slow.md
          - no/oslo-balboa-weekend.md
          - no/swing-brother-swing.md
          - no/vintage-swing-night.md
      - 波兰:
        - 时间线: pl/index.md
        - 按城市划分: pl/by_city.md
        - 主办城市: pl/host_cities.md
        - 已收录活动:
          - pl/lindy-szaus-birthday-jam.md
          - pl/lindy-hop-non-stop.md
          - pl/rock-the-balboa.md
          - pl/dragon-swing-festival.md
      - 俄罗斯:
        - 时间线: ru/index.md
        - 按城市划分: ru/by_city.md
        - 主办城市: ru/host_cities.md
        - 已收录活动:
          - ru/fast-pete.md
          - ru/balboa-dacha.md
          - ru/moscow-comes-around.md
      - 瑞典:
        - 时间线: se/index.md
        - 按城市划分: se/by_city.md
        - 主办城市: se/host_cities.md
        - 已收录活动:
          - se/heedman-dance-camp.md
          - se/herrang-dance-camp.md
          - se/gothenburg-queer-lindy-festival.md
          - se/the-snowball.md
      - 斯洛文尼亚:
        - 时间线: si/index.md
        - 按城市划分: si/by_city.md
        - 主办城市: si/host_cities.md
        - 已收录活动:
          - si/haniBal-balboa-festival.md
          - si/vintage-swing-festival.md
      - 英国:
        - 时间线: uk/index.md
        - 按城市划分: uk/by_city.md
        - 主办城市: uk/host_cities.md
        - 已收录活动:
          - uk/lindy-in-the-sky-with-diamonds.md
          - uk/hep-to-the-hive.md
          - uk/bal-break-at-the-livermead-cliff.md
          - uk/belta-blues.md
          - uk/edinburgh-lindy-exchange.md
          - uk/fast-feet-festival.md
          - uk/nighthawks-summer-weekender.md
          - uk/mersey-swing-smackdown.md
          - uk/northern-slow-bal-celebration.md
          - uk/swing-city-brighton-weekend.md
          - uk/atomic-cocktail.md
          - uk/cambridge-lindy-exchange.md
          - uk/the-savoy-jazz-jam.md
    - 大洋洲:
      - 澳大利亚:
        - 时间线: au/index.md
        - 按城市划分: au/by_city.md
        - 主办城市: au/host_cities.md
        - 已收录活动:
          - au/the-adelaide-lindy-exchange.md
          - au/hullabaloo.md
          - au/jurassic-bal.md
          - au/brisbane-swing-thing.md
          - au/gold-coast-lindy-fest.md
          - au/winter-swing-festival.md
          - au/sydney-lindy-exchange.md
          - au/boogie-down-south.md
          - au/brisbane-balboa-weekend.md
          - au/spring-mini-blues-weekend.md
          - au/lindy-rovale.md
          - au/melbourne-lindy-exchange.md
          - au/remy-n-ramona-weekend.md
  - 组织: https://swing.kids/zh-Hans
  - references.md
  - 更新日志: https://github.com/swingdance/events/commits/main/
  - 关于:
    - support.md
    - 隐私与条款:
      - privacy.md
      - terms.md
  - + 添加组织/活动: https://swing.kids/zh-Hans/submit
