INHERIT: '../base.yml'

docs_dir: '../../src/en'
site_dir: '../../build'

theme:
  name: material
  language: en

plugins:
  - search
  - tags:
      tags_file: tags.md
  - social:
      cards_layout_options:
        background_color: "#14151A"

site_description: 'A collection of swing dance events from around the world.'
nav:
  - Home:
    - Timeline: index.md
    - Tags: tags.md
    #- Archives:

  - Regions:
    - All: regions.md
    - America:
      - Canada:
        - Timeline: ca/index.md
        - Events by City: ca/by_city.md
        - Host Cities: ca/host_cities.md
        - Collected Events:
          - ca/victoria-lindy-exchange.md
          - ca/stardust-festival.md
          - ca/rhythm-city-mess-around.md
          - ca/lindy-harvest.md
          - ca/cats-corner-exchange.md
          - ca/vancouver-balboa-mini-fest.md
          - ca/capital-city-stomp.md
      - Chile:
        - Timeline: cl/index.md
        - Events by City: cl/by_city.md
        - Host Cities: cl/host_cities.md
        - Collected Events:
          - cl/lindy-poh.md
      - Mexico:
        - Timeline: mx/index.md
        - Events by City: mx/by_city.md
        - Host Cities: mx/host_cities.md
        - Collected Events:
          - mx/mexico-lindy-querido.md
          - mx/guadalajara-lindy-exchange.md
          - mx/lindy-n-balboa-maya-fest.md
      - United States:
        - Timeline: us/index.md
        - Events by City: us/by_city.md
        - Host Cities: us/host_cities.md
        - Collected Events:
          - us/california-balboa-classic.md
          - us/hot-rhythm-holiday.md
          - us/lindyfest.md
          - us/bal-week.md
          - us/back-home-again.md
          - us/san-diego-balboa-and-lindy-exchange.md
          - us/flying-home.md
          - us/camp-hollywood.md
          - us/cincy-hop.md
          - us/rittenhopalooza.md
          - us/summer-swing-fest.md
          - us/swing-out-new-hampshire.md
          - us/the-uptown-swingout.md
          - us/blues-fusion-dfw.md
          - us/cowtown-jamborama.md
          - us/express-track-blues.md
          - us/great-lakes-balboa-escape.md
          - us/hot-night-fusion-weekend.md
          - us/lindy-on-the-rocks.md
          - us/new-york-lindy-exchange.md
          - us/rhythm-shuffle.md
          - us/blues-muse.md
          - us/bubble-city-bash.md
          - us/emerald-city-blues-festival.md
          - us/stl-getdown.md
          - us/the-american-lindy-hop-championships.md
          - us/whistle-stop.md
          - us/austin-lindy-exchange.md
          - us/breaking-bal-swing-n-blues-weekend.md
          - us/hot-jazz-jamboree.md
          - us/stardust-slow-balboa-weekend.md
          - us/stompology.md
          - us/stormy-weather-jazz-festival.md
    - Asia:
      - Armenia:
        - Timeline: am/index.md
        - Events by City: am/by_city.md
        - Host Cities: am/host_cities.md
        - Collected Events:
          - am/swing-road-armenia.md
      - China:
        - Timeline: cn/index.md
        - Events by City: cn/by_city.md
        - Host Cities: cn/host_cities.md
        - Collected Events:
          - cn/beijing-balboa-travel.md
          - cn/all-balboa-exchange.md
          - cn/its-solo-king.md
          - cn/groove-the-bluesy-bay.md
          - cn/lindy-hotpot.md
          - cn/balboa-spring-camp.md
          - cn/bouncy-chengdu.md
          - cn/shanghai-blues-camp.md
          - cn/beijing-balboa-fever.md
          - cn/camp-california-weekend.md
          - cn/canton-swing-festival.md
          - cn/jumpin-swing.md
          - cn/jumping-swing.md
          - cn/nanjing-lindy-festival.md
          - cn/balboa-festival.md
          - cn/dragon-boat-swing-camp.md
          - cn/jump-for-joy.md
          - cn/swing-in-dalifornia.md
          - cn/bal-in-beijing.md
          - cn/balboa-festival-shanghai.md
          - cn/funs-swing-exchange.md
          - cn/blues-heat.md
          - cn/blues-in-green.md
          - cn/jazz-do-it.md
          - cn/swing-feast.md
          - cn/westlake-swing-carnival.md
          - cn/beijing-blues-bush.md
          - cn/golden-bal-week.md
          - cn/island-swing.md
          - cn/swing-paramount.md
          - cn/womens-jazzination.md
          - cn/hop-the-bay.md
          - cn/shanghai-balboa-weekend.md
          - cn/swing-to-the-stars.md
          - cn/swingtime-ball.md
          - cn/foshan-x-korea-exchange.md
          - cn/shanghai-lindy-festival.md
      - Hong Kong:
        - Timeline: hk/index.md
        - Events by City: hk/by_city.md
        - Host Cities: hk/host_cities.md
        - Collected Events:
          - hk/harbourside-swing-fest.md
      - Indonesia:
        - Timeline: id/index.md
        - Events by City: id/by_city.md
        - Host Cities: id/host_cities.md
        - Collected Events:
          - id/bali-lindy-exchange.md
      - Japan:
        - Timeline: jp/index.md
        - Events by City: jp/by_city.md
        - Host Cities: jp/host_cities.md
        - Collected Events:
          - jp/balboa-lab-tea-party.md
          - jp/chill-balboa-social.md
          - jp/swingin-n-hoppin-sapporp.md
          - jp/tomodachi-swing.md
          - jp/bal-in-tokyo.md
          - jp/swing-jack.md
          - jp/osaka-lindy-exchange.md
          - jp/tokyo-balboa-weekend.md
      - South Korea:
        - Timeline: kr/index.md
        - Events by City: kr/by_city.md
        - Host Cities: kr/host_cities.md
        - Collected Events:
          - kr/blues-alive.md
          - kr/asia-balboa-exchange.md
          - kr/camp-swing-it.md
          - kr/rhythm-korea.md
          - kr/champions-cup-korea.md
          - kr/bal-hop.md
          - kr/jump-to-berlin.md
          - kr/seoul-lindy-fest.md
          - kr/korean-balboa-weekend.md
          - kr/savoy-cup-asia.md
      - Thailand:
        - Timeline: th/index.md
        - Events by City: th/by_city.md
        - Host Cities: th/host_cities.md
        - Collected Events:
          - th/breezy-balboa.md
          - th/swing-era.md
          - th/diga-diga-doo.md
      - Turkey:
        - Timeline: tr/index.md
        - Events by City: tr/by_city.md
        - Host Cities: tr/host_cities.md
        - Collected Events:
          - tr/jumpin-at-istanbul.md
      - Taiwan:
        - Timeline: tw/index.md
        - Events by City: tw/by_city.md
        - Host Cities: tw/host_cities.md
        - Collected Events:
          - tw/cheek-to-cheek-swing-festival.md
          - tw/what-the-pa.md
    - Europe:
      - Belgium:
        - Timeline: be/index.md
        - Events by City: be/by_city.md
        - Host Cities: be/host_cities.md
        - Collected Events:
          - be/boulevard-blues.md
      - Switzerland:
        - Timeline: ch/index.md
        - Events by City: ch/by_city.md
        - Host Cities: ch/host_cities.md
        - Collected Events:
          - ch/bal-inspiration.md
          - ch/shag-delight.md
          - ch/shake-that-lake.md
          - ch/rocky-balberna.md
          - ch/stir-it.md
      - Czechia:
        - Timeline: cz/index.md
        - Events by City: cz/by_city.md
        - Host Cities: cz/host_cities.md
        - Collected Events:
          - cz/bal-love.md
          - cz/slow-bal-love.md
      - Germany:
        - Timeline: de/index.md
        - Events by City: de/by_city.md
        - Host Cities: de/host_cities.md
        - Collected Events:
          - de/slow-balboa-weekend-munich.md
          - de/swing-it-berlin.md
          - de/berlin-balboa-weekend.md
          - de/rock-that-swing-festival.md
          - de/b-t-switch.md
          - de/swingcake-tubingen.md
          - de/harvest-moon-swing-dance-camp.md
          - de/lindy-hop-trainingslager.md
          - de/shag-ahoi.md
          - de/velo-swing-festival.md
          - de/augsburg-balboa-festival.md
          - de/flying-feet-stuttgart.md
          - de/hannover-swing-exchange.md
          - de/hully-blues.md
          - de/swing-it-konstanz.md
          - de/are-you-syncopated.md
          - de/blues-dance-retreat.md
          - de/da-solo-jazz-festival.md
          - de/lindy-cake.md
          - de/mainhatten-shuffle.md
          - de/munich-balboa-n-shag-weekend.md
          - de/swing-man-tau.md
          - de/swingomania.md
          - de/augsburg-boogie-festival.md
          - de/balboa-date-stuttgart.md
          - de/broadway-swing.md
          - de/hully-hop-swing-farm.md
          - de/swingin-charlie.md
          - de/swinging-marzipan-lubeck.md
          - de/autumn-leaves-the-pott.md
          - de/xma-swing.md
      - Denmark:
        - Timeline: dk/index.md
        - Events by City: dk/by_city.md
        - Host Cities: dk/host_cities.md
        - Collected Events:
          - dk/why-not-aarhus-lindy-exchange.md
          - dk/copenhagen-balboa-weekend.md
          - dk/falling-for-swing.md
      - Spain:
        - Timeline: es/index.md
        - Events by City: es/by_city.md
        - Host Cities: es/host_cities.md
        - Collected Events:
          - es/move-your-bottom.md
          - es/sevilla-swing-festival.md
          - es/festival-swing-monachil.md
          - es/jazz-n-swing-gasteiz-festival.md
          - es/metropoli-fest.md
          - es/morella-swing-weekend.md
          - es/barcelona-lindy-exchange.md
          - es/barcelona-shag-festival.md
          - es/calpe-swing-fiesta.md
          - es/swim-out-costa-brava.md
          - es/swing-a-esgaya.md
          - es/the-jump.md
          - es/cadiz-swing-festival.md
          - es/donosti-belle-swing-festival.md
          - es/mojo-swing-tropical-fest.md
          - es/smile-trio-weekend.md
          - es/stomp-your-feet.md
          - es/swing-ciudad-real.md
          - es/swing-fest-malaga.md
          - es/barcelona-balboa-festival.md
          - es/espanish-blues-festival.md
      - France:
        - Timeline: fr/index.md
        - Events by City: fr/by_city.md
        - Host Cities: fr/host_cities.md
        - Collected Events:
          - fr/the-battle.md
          - fr/tours-n-swing.md
          - fr/swing-art-festival.md
          - fr/anduze-jazz-dance-camp.md
          - fr/summer-camp-balboa-week.md
          - fr/summer-camp-lindy-week.md
          - fr/la-plagne-swing.md
          - fr/summer-camp-blues-week.md
          - fr/savoie-balboa-festival.md
          - fr/tours-n-balboa.md
          - fr/rainy-blues.md
          - fr/toulouse-swing-exchange.md
          - fr/lyon-swing-festival.md
          - fr/swingamann.md
          - fr/european-balboa-festival.md
      - Greece:
        - Timeline: gr/index.md
        - Events by City: gr/by_city.md
        - Host Cities: gr/host_cities.md
        - Collected Events:
          - gr/crete-on-the-beat.md
          - gr/wild-west-festival.md
      - Italy:
        - Timeline: it/index.md
        - Events by City: it/by_city.md
        - Host Cities: it/host_cities.md
        - Collected Events:
          - it/crazy-blues.md
          - it/keep-on-swingin.md
          - it/milan-balboa-weekend.md
          - it/tuscany-balboa-weekend.md
          - it/swing-in-roma.md
          - it/roma-balboa-weekend.md
          - it/swing-train-festival.md
          - it/sunny-slide-swing-fest.md
          - it/swing-in-the-amalfi-coast.md
          - it/bal-n-lindy-vintage-festival.md
          - it/balboario.md
          - it/policoro-in-swing.md
          - it/sicily-swing-fest.md
          - it/swingala.md
          - it/swing-n-milan.md
      - Lithuania:
        - Timeline: lt/index.md
        - Events by City: lt/by_city.md
        - Host Cities: lt/host_cities.md
        - Collected Events:
          - lt/uptown-rhythm.md
          - lt/bluesila.md
          - lt/what-a-jazz-summer-camp.md
          - lt/all-lithuanian-weekend.md
          - lt/vilnius-shag-festival.md
      - Luxembourg:
        - Timeline: lu/index.md
        - Events by City: lu/by_city.md
        - Host Cities: lu/host_cities.md
        - Collected Events:
          - lu/swing-the-abbey.md
      - Netherlands:
        - Timeline: nl/index.md
        - Events by City: nl/by_city.md
        - Host Cities: nl/host_cities.md
        - Collected Events:
          - nl/the-mess-around.md
          - nl/swing-dom.md
          - nl/the-vintage-battle-of-the-bands.md
      - Norway:
        - Timeline: no/index.md
        - Events by City: no/by_city.md
        - Host Cities: no/host_cities.md
        - Collected Events:
          - no/scandinavian-shuffle.md
          - no/winter-jump.md
          - no/bal-heim.md
          - no/boogie-feets-festival.md
          - no/slow-balboa-boost.md
          - no/o-slow.md
          - no/oslo-balboa-weekend.md
          - no/swing-brother-swing.md
          - no/vintage-swing-night.md
      - Poland:
        - Timeline: pl/index.md
        - Events by City: pl/by_city.md
        - Host Cities: pl/host_cities.md
        - Collected Events:
          - pl/lindy-szaus-birthday-jam.md
          - pl/lindy-hop-non-stop.md
          - pl/rock-the-balboa.md
          - pl/dragon-swing-festival.md
      - Russia:
        - Timeline: ru/index.md
        - Events by City: ru/by_city.md
        - Host Cities: ru/host_cities.md
        - Collected Events:
          - ru/balboa-dacha.md
          - ru/moscow-comes-around.md
      - Sweden:
        - Timeline: se/index.md
        - Events by City: se/by_city.md
        - Host Cities: se/host_cities.md
        - Collected Events:
          - se/heedman-dance-camp.md
          - se/herrang-dance-camp.md
          - se/gothenburg-queer-lindy-festival.md
          - se/the-snowball.md
      - Slovenia:
        - Timeline: si/index.md
        - Events by City: si/by_city.md
        - Host Cities: si/host_cities.md
        - Collected Events:
          - si/haniBal-balboa-festival.md
          - si/vintage-swing-festival.md
      - United Kingdom:
        - Timeline: uk/index.md
        - Events by City: uk/by_city.md
        - Host Cities: uk/host_cities.md
        - Collected Events:
          - uk/lindy-in-the-sky-with-diamonds.md
          - uk/hep-to-the-hive.md
          - uk/bal-break-at-the-livermead-cliff.md
          - uk/belta-blues.md
          - uk/edinburgh-lindy-exchange.md
          - uk/fast-feet-festival.md
          - uk/nighthawks-summer-weekender.md
          - uk/mersey-swing-smackdown.md
          - uk/northern-slow-bal-celebration.md
          - uk/swing-city-brighton-weekend.md
          - uk/atomic-cocktail.md
          - uk/cambridge-lindy-exchange.md
          - uk/the-savoy-jazz-jam.md
    - Oceania:
      - Australia:
        - Timeline: au/index.md
        - Events by City: au/by_city.md
        - Host Cities: au/host_cities.md
        - Collected Events:
          - au/the-adelaide-lindy-exchange.md
          - au/hullabaloo.md
          - au/jurassic-bal.md
          - au/brisbane-swing-thing.md
          - au/gold-coast-lindy-fest.md
          - au/winter-swing-festival.md
          - au/sydney-lindy-exchange.md
          - au/boogie-down-south.md
          - au/brisbane-balboa-weekend.md
          - au/spring-mini-blues-weekend.md
          - au/lindy-rovale.md
          - au/melbourne-lindy-exchange.md
          - au/remy-n-ramona-weekend.md
  - Orgs: https://swing.kids
  - references.md
  - Changelogs: https://github.com/swingdance/events/commits/main/
  - About:
    - support.md
    - Privacy & Terms:
      - privacy.md
      - terms.md
  - + Submit Org/Event: https://swing.kids/submit
